version: '2'
services:
  achecker:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
  mysql:
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pw
